# Generated by Django 5.2.3 on 2025-07-02 23:53

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', models.CharField(default=core.models.UUIDBaseModel.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('pack_unit', models.CharField(choices=[('BX', 'BOX'), ('PCS', 'PIECES'), ('BG', 'BAG'), ('CONT', 'CONTAINER'), ('JR', 'JAR'), ('EA', 'EACH'), ('PK', 'PACK'), ('JG', 'JUG'), ('BT', 'BOTTLE'), ('CAN', 'CAN'), ('TUB', 'TUB'), ('CT', 'CARTON'), ('SAC', 'SACK')], default='EA', max_length=5)),
                ('price_in_micros', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
