# Generated by Django 5.2.3 on 2025-06-27 01:54

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', models.CharField(default=core.models.UUIDBaseModel.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemPack',
            fields=[
                ('uuid', models.CharField(default=core.models.UUIDBaseModel.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pack_unit', models.CharField(default='pcs', max_length=50)),
            ],
            options={
                'db_table': 'item_packs',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
            ],
            options={
                'db_table': 'catalog_items',
            },
            bases=('inventory.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itempack'),
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('created_by', models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to='users.user')),
            ],
            options={
                'db_table': 'user_items',
            },
            bases=('inventory.item',),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'pack')},
        ),
    ]
