# Generated by Django 5.2.3 on 2025-06-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
        migrations.AlterModelTable(
            name='itempack',
            table='item_packs',
        ),
    ]
