# Generated by Django 5.2.3 on 2025-06-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pack_unit',
            field=models.CharField(choices=[('BX', 'BOX'), ('PCS', 'PIECES'), ('BG', 'BAG'), ('CONT', 'CONTAINER'), ('JR', 'JAR'), ('EA', 'EACH'), ('PK', 'PACK'), ('JG', 'JUG'), ('BT', 'BOTTLE'), ('CAN', 'CAN'), ('TUB', 'TUB'), ('CT', 'CARTON'), ('SAC', 'SACK')], default='EA', max_length=5),
        ),
    ]
