# Generated by Django 5.2.3 on 2025-06-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_pack_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
    ]
