# Generated by Django 5.2.3 on 2025-06-28 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='remaining_percentage',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
