# Generated by Django 5.2.3 on 2025-06-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_remaining_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='remaining_percentage',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_quantity',
        ),
    ]
