# Generated by Django 5.2.3 on 2025-06-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='list',
            table='lists',
        ),
        migrations.AlterModelTable(
            name='listitem',
            table='list_items',
        ),
    ]
