# Generated by Django 5.2.4 on 2025-07-05 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_list_created_by_alter_listitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.list'),
        ),
    ]
