# Generated by Django 5.2.4 on 2025-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_alter_listitem_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
