# Generated by Django
from django.db import migrations

def create_system_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.get_or_create(
        uuid='00000000-0000-0000-0000-000000000000',
        defaults={
            'email': 'system@example.com',
            'name': 'System User',
            'is_active': False,
            'is_staff': False,
            'is_superuser': False,
            'password': '',  # No password
            'created_by': None,  # No creator for system user
        }
    )

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_make_created_by_nullable'),
    ]

    operations = [
        migrations.RunPython(create_system_user),
    ]