# Generated by Django 6.0.1 on 2026-02-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
