# Generated by Django 5.2.3 on 2025-07-02 23:53

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('uuid', models.CharField(default=core.models.UUIDBaseModel.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('storage_type', models.CharField(choices=[('Frozen', 'Frozen'), ('Cold', 'Fridge'), ('Dry', 'Cupboard')], default='Dry', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'storage_locations',
            },
        ),
        migrations.CreateModel(
            name='StorageLocationItem',
            fields=[
                ('uuid', models.CharField(default=core.models.UUIDBaseModel.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('remaining_percentage', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'storage_location_items',
            },
        ),
    ]
