# Generated by Django 5.2.3 on 2025-06-28 01:20

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('uuid', models.CharField(default=core.models.UUIDBaseModel.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('storage_type', models.CharField(choices=[('Frozen', 'Frozen'), ('Cold', 'Fridge'), ('Dry', 'Cupboard')], default='Dry', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_by', models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='users.user')),
            ],
            options={
                'db_table': 'storage_locations',
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='StorageLocationItem',
            fields=[
                ('uuid', models.CharField(default=core.models.UUIDBaseModel.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='storage.storagelocation')),
            ],
            options={
                'db_table': 'storage_location_items',
                'unique_together': {('item', 'storage_location')},
            },
        ),
    ]
