# Generated by Django 5.2.3 on 2025-06-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_table_alter_itempack_table'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoredItem',
            new_name='StoreageLocationItem',
        ),
        migrations.AlterModelTable(
            name='storagelocation',
            table='storage_locations',
        ),
        migrations.AlterModelTable(
            name='storeagelocationitem',
            table='storage_location_items',
        ),
    ]
