# Generated by Django 5.2.3 on 2025-06-28 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storagelocation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='storagelocationitem',
            name='remaining_percentage',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
