# Generated by Django 5.2.4 on 2025-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_storagelocation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storagelocationitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
